### PR TITLE
Fix style sizes

### PR DESCRIPTION
**Pull request by kulmann**
Needed to get rid of the `scoped` props. This blew up the css bundle size to 7 MB instead of 400 KB.

Fixes https://github.com/owncloud/owncloud-design-system/issues/1049

### CODE REVIEW

**Comment by kulmann** [comment]
Also, CI time is back to 3min 20sec with this PR (coming from 4min 15sec).

**Review by LukasHirt — APPROVED** [review]
Do you know why the `scoped` styles actually caused the bump in the size? Feels super strange that this would have such a side-effect.

**Comment by kulmann** [comment]
> Do you know why the `scoped` styles actually caused the bump in the size? Feels super strange that this would have such a side-effect.

Somehow scoped styles are cloning **all** styles (not just the ones in the scope of the component).
Looks like this in the css file: `.oc-accordion-title[data-v-33c90a04]`.
This looks like a webpack configuration issue, but thinking about it I think that the styles should not be scoped to give developers a chance to re-use the classes. Or do we explicitly not want them to be reusable?

**Comment by LukasHirt** [comment]
> styles should not be scoped to give developers a chance to re-use the classes. Or do we explicitly not want them to be reusable?

Hmm, as we have them tied closely to the component, is there actually a use case for using them without those components? I'd prefer to always use the components. But if there's some use case I am overlooking then sure, let's have them re-usable. Of course, an exception would be some utility classes but those shouldn't live in a component.

I was actually super happy that the styles would be scoped and wouldn't have a chance to fight with any other classes in consuming apps.

**Comment by kulmann** [comment]
Hmmmmm... true, true.
I'll create an issue that we want to solve it to have component styles scoped again.

**Pull request merged**
