### PR TITLE
Added docs about escaping translations

### PR DESCRIPTION
**Pull request by LukasHirt**
image

### CODE REVIEW

**Comment by LukasHirt** [comment]
@C0rby for some reason I can't add you as a reviewer because it doesn't find you there 🤷‍♂ Pls check these docs as well :pray:

**Comment by PVince81** [comment]
After reading the explanation it doesn't feel clear enough.

Wasn't this about avoiding double escaping ? Is the undesirable result the double escaping ? Might be good to be clear about this, because I usually shiver when I read disabling escaping for user controlled values. So we better make sure we are still on the safe side and say so explicitly (probably the thing about the mustache syntax)

**Comment by DeepDiver1975** [comment]
Is this something for the design system? We have no translations in here and we are also not forcing any project on the tooling.

From my pov this needs to go into the docs for phoenix .... somewhere .....

**Comment by LukasHirt** [comment]
> After reading the explanation it doesn't feel clear enough.

I'll try to go more into details :wink:

**Comment by LukasHirt** [comment]
> Is this something for the design system?

@DeepDiver1975 This was discussed recently and the reasoning behind this is to have the guidelines united and since we are already including accessibility and design ones there (plus some internationalization already as well), seems ok to have there also parts about the actual code.

**Comment by LukasHirt** [comment]
@PVince81 Docs adjusted.

**Comment by PVince81** [comment]
I also have mixed feelings about this but agree that having all in one place is slightly better.
Let's go with that for now.

**Comment by PVince81** [comment]
thinking... adding the docs to Phoenix core will not help getting awareness for when we split Phoenix files and other extensions, as we'd need to duplicate the docs to these repos if they all use easygettext.

and some extensions might not use easygettext at all.

anyway, existing doc is better than no doc at all

**Comment by PVince81** [comment]
raised https://github.com/owncloud/owncloud-design-system/issues/642

**Pull request merged**
