### PR TITLE
Bugfix/fix search bar

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Screenshot_2019-03-26 ownCloud Design System

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> UX: This needs a send/search button

agreed - I failed to include a button :see_no_evil: - help appreciated ... feel free to commit into this branch - THX

**Comment by felixheidecke** [comment]
I'd also move the search icon to the left and replace it with the loading spinner if it's loading. Then we have enough clutter free space for an actual button on the right.

**Comment by felixheidecke** [comment]
Having the search query to the right increases the risk of running into width problems where we would need to ellipse the query on adjacent objects or smaller horizontal width.

**Comment by DeepDiver1975** [comment]
@felixheidecke 
- [ ] clearing input does not emit the change event
- [ ] we might want an option to remove the button
Screenshot from 2019-03-27 12-56-35

**Comment by felixheidecke** [comment]
There is the `button="false"` option to get rid of the button.

**Pull request merged**
