### PR TITLE
[ci] rearrange ci steps to optimize runtime

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Break the testing pipeline step into lint, build and testing pipelines so that the CI can fail faster.

## Related Issue

- Fixes https://github.com/owncloud/owncloud-design-system/issues/1357

## How Has This Been Tested?

:robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by kiranparajuli589** [comment]
IMO `lint` steps can also be separated from the test pipe to separate one 🤔

**Comment by dpakach** [comment]
> IMO `lint` steps can also be separated from the test pipe to separate one  if fails on lint, do not run tests

the problem is that we need to install dependencies for all steps, and since the lint pipeline doesn't take much time (20 - 30 seconds), it is not required IMO

**Review by phil-davis — APPROVED** [review]
LGTM - this leaves the lint and unit tests in a separate pipeline that can run and fail early if there is a lint or unit test failure. The "build docs" and "build system" steps run in a separate pipeline that does not delay the unit test result....

It looks like it saves a couple of minutes elapsed time for a successful result.

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
Wait a sec

**Comment by phil-davis** [comment]
Sorry - I  pressed merge!

**Comment by LukasHirt** [comment]
@dpakach Why getting rid of `depends_on` in build steps? It actually makes those steps run in parallel so saving ~2mins per run.

**Comment by pascalwengerter** [comment]
> Sorry - I pressed merge!

All good, opened a PR to revert this commit and commented in the (re-opened) ticket what I originally had in mind

**Pull request merged**
