### PR TITLE
Added slots in TabItem, Breadcrumb and SidebarNavItem

### PR DESCRIPTION
**Pull request by LukasHirt**
Added slots in TabItem, Breadcrumb and SidebarNavItem

### CODE REVIEW

**Comment by LukasHirt** [comment]
Added some changes into the description of the text and title props about how they are used with slots. Not sure if you meant it like this so let me know if I got this one wrong.

**Comment by DeepDiver1975** [comment]
> Added some changes into the description of the text and title props about how they are used with slots. Not sure if you meant it like this so let me know if I got this one wrong.

I was talking about the ```<docs>``` section at the end of the file. we shall use the components down there with the slots ...

**Comment by LukasHirt** [comment]
I see. Should be fixed now.

**Comment by DeepDiver1975** [comment]
> I see. Should be fixed now.

better - thx

**Pull request merged**
