### PR TITLE
release: 7.5.0

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
LGTM

**Review by kulmann — CHANGES_REQUESTED** [review]
Please also set the new version in the sonar-project.properties file:
https://github.com/owncloud/owncloud-design-system/blob/a0d9cd2827e4912afc417d43506496e162320500/sonar-project.properties#L5

(that's new in the release process - 1.0 in there was just a placeholder)

**Comment by pascalwengerter** [comment]
> Please also set the new version in the sonar-project.properties file:
> 
> https://github.com/owncloud/owncloud-design-system/blob/a0d9cd2827e4912afc417d43506496e162320500/sonar-project.properties#L5
> 
> (that's new in the release process - 1.0 in there was just a placeholder)

Might then be also nice to add this as a step to [the release docs](https://owncloud.design/#/Versioning%20%26%20Release)

**Comment by LukasHirt** [comment]
> Please also set the new version in the sonar-project.properties file

Done but why do we need this at all?

**Comment by kulmann** [comment]
> > Please also set the new version in the sonar-project.properties file
> 
> Done but why do we need this at all?

Sonarcloud dashboard is public and shows the version. ;-) And it utilizes the version for the [activity history](https://sonarcloud.io/project/activity?id=owncloud_web). But needs to be set manually apparently.

**Review by kulmann — APPROVED** [review]
LGTM 👍

**Pull request merged**
