### PR TITLE
Add OcLoader

### PR DESCRIPTION
**Pull request by felixheidecke**
Closes: https://github.com/owncloud/owncloud-design-system/issues/103

### CODE REVIEW

**Comment by felixheidecke** [comment]
I also added the _Loader to Loading_ demo in the pattern library. @DeepDiver1975 Not sure if we need this?!

**Comment by DeepDiver1975** [comment]
> I also added the _Loader to Loading_ demo in the pattern library. @DeepDiver1975 Not sure if we need this?!

this can be of great help in some cases - THX

**Comment by DeepDiver1975** [comment]
Question is where to put such stuff ... this is more example code ... hmmm

I see these options:
- add this as template
- add this to the components oc-loader and oc-progress

**Comment by DeepDiver1975** [comment]
>     * add this as template

@felixheidecke let's move this to a new template for now - THX

**Pull request merged**
