### PR TITLE
Passover the `hover` option from `oc-table`

### PR DESCRIPTION
**Pull request by tlan16**
## Description
The proposed changes expose the `hover` option of `oc-table` to `oc-table-files`.

## Related Issue

- None.

## Motivation and Context

This allows the user of `oc-table-files` to enable the hover effect. 

## How Has This Been Tested?

- hand tested on local development environment.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:
None.

### CODE REVIEW

**Comment by pascalwengerter** [comment]
@tlan16 thank you for this PR! 
Could you add an `enhancement` changelog item in the `changelog/unreleased/` folder? You can check older releases for templates on how to structure that file.

I'll also have to check how your suggestion works together with the recently introduced drag-and-drop background styling in OcTableFiles 😉

**Comment by tlan16** [comment]
Can someone advise me how to run test for this project? Here's my attempt:

```shell
➜  owncloud-design-system git:(master) yarn test
Found existing alias for "yarn test". You should use: "yt"
yarn run v1.22.11
$ jest --config ./jest.conf.js --coverage
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
No files found in /home/frank/Documents/owncloud_web/node_modules/owncloud-design-system.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern:  - 0 matches
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```shell
/usr/bin/node /home/frank/Documents/owncloud_web/node_modules/owncloud-design-system/src/components/table/OcTableFiles.spec.js
(node:23088) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/frank/Documents/owncloud_web/node_modules/owncloud-design-system/src/components/table/OcTableFiles.spec.js:1
import { mount } from "@vue/test-utils"
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

Process finished with exit code 1
```

**Comment by pascalwengerter** [comment]
> ```shell
> No files found in /home/frank/Documents/owncloud_web/node_modules/owncloud-design-system.
> ```

Hey, from that line it seems to run tests from within the node_modules folder inside the [web repo](https://github.com/owncloud/web), but we don't ship tests with our bundle. You should be able to run the tests if you clone this repo here locally, set it up via `yarn install` and then run `yarn test` (or your alias `yt`)

**Comment by tlan16** [comment]
> > ```shell
> > No files found in /home/frank/Documents/owncloud_web/node_modules/owncloud-design-system.
> > ```
> 
> Hey, from that line it seems like you are trying to run tests from within the node_modules folder inside the [web repo](https://github.com/owncloud/web), but we don't ship tests with our bundle. You should be able to run the tests if you clone this repo here locally, set it up via `yarn install` and then run `yarn test` (or your alias `yt`)

Hi @pascalwengerter , thank for your reply. I almost forgot my little trick and I'm not aware of that side effect (of the trick). I added tests for the hover effect. Let me know if you need anything refactored.

**Comment by rpocklin** [comment]
Hi @pascalwengerter any chance for this to be looked at?

**Comment by pascalwengerter** [comment]
> Hi @pascalwengerter any chance for this to be looked at?

Hey @rpocklin @tlan16 sorry for not getting back to this faster. We recently implemented hover styling on drag&drop and need to check how those two can/should go together 😉 

Removing the recently added (JS-based) drag&drop-hover in favor of your (CSS-based) hover styling would probably be preferred, let me take a look regarding UX later!

**Comment by rpocklin** [comment]
@pascalwengerter Hi just checking how you went with the hover / drag and drop styling combination for this PR to be accepted?

**Review by pascalwengerter — APPROVED** [review]
Finally got around testing this and actually feels pretty neat, thanks for the contribution!

**Comment by pascalwengerter** [comment]
I'll add an example and a changelog item in a dedicated PR in the meantime

**Comment by rpocklin** [comment]
Thank you 👍

**Pull request merged**
