### PR TITLE
Fix link to owncloud.com/wp-content/uploads/.. SVG

### LINKED ISSUE #860: Fix ownCloud logo in documentation
The ownCloud logo is used in the ODS documentation (e.g. in the sidebar component). It is fetched from an external source - which has recently been removed. Now the logo is broken in documentation, see screenshot.

**Decision needed**: embed the logo in the docs folder within this repository, or just fix link to the external source?
Please note that the logo will not be shipped with the npm package. It's only part of the documentation.

Screenshot 2020-09-15 at 14 23 28

### PR DESCRIPTION
**Pull request by pascalwengerter**
Fixes #860, @kulmann & @LukasHirt please let me know if you want to put the `.svg` directly in the repo (this PR just updates the reference to the ownCloud.com website)!

### CODE REVIEW

**Comment by LukasHirt** [comment]
You actually uncovered a different issue with this 🙈 As we switched version of ODS to Apache, we cannot include ownCloud logo in the repo anymore otherwise anyone could use it as they want. Could you pls switch this to some placeholder logo? Having the SVG file directly in the repo would be nice but I wouldn't see this as a blocker for this PR.

**Comment by pascalwengerter** [comment]
Uh boy 😅 yeah I'll take care of this and add some placeholder logo!

**Comment by pascalwengerter** [comment]
@LukasHirt how do you like this one? 😉 Updated the PR accordingly

Screenshot 2021-02-23 at 20 18 05

**Review by LukasHirt — APPROVED** [review]
Awesome! ❤️

**Pull request merged**
