### PR TITLE
Implement labels and descriptions for text input fields

### PR DESCRIPTION
**Pull request by JammingBen**
* Remove placeholders
* Add required label to text inputs
* Add optional description message to text inputs
* Add `aria-describedby` which either references the description (if given), or an error/warning (if given)
* Add `aria-invalid` property

### CODE REVIEW

**Review by fschade — APPROVED** [review]
LGMT 🚀

**Comment by JammingBen** [comment]
@kulmann Applied the naming changes as discussed 🙂

**Review by kulmann — CHANGES_REQUESTED** [review]
There are other components in the design system which rely on the `oc-text-input` component, like the search for example. Since those don't necessarily require a visible label, it makes sense IMO that we change the implementation of the components which depend on `oc-text-input` to not use it anymore + replicate the necessary styling (CSS duplication is fine here, since we want to move towards really standalone components). Could you look into that before we merge this PR here?

**Comment by JammingBen** [comment]
> There are other components in the design system which rely on the oc-text-input component, like the search for example. Since those don't necessarily require a visible label, it makes sense IMO that we change the implementation of the components which depend on oc-text-input to not use it anymore + replicate the necessary styling (CSS duplication is fine here, since we want to move towards really standalone components). Could you look into that before we merge this PR here?

@kulmann Hmm but we would also need to implement the descriptions, errors etc. again for each text input. Not necessarily for the search component, but for modal e.g. Maybe it is easier to provide an option to hide the label?

**Comment by kulmann** [comment]
> > There are other components in the design system which rely on the oc-text-input component, like the search for example. Since those don't necessarily require a visible label, it makes sense IMO that we change the implementation of the components which depend on oc-text-input to not use it anymore + replicate the necessary styling (CSS duplication is fine here, since we want to move towards really standalone components). Could you look into that before we merge this PR here?
> 
> @kulmann Hmm but we would also need to implement the descriptions, errors etc. again for each text input. Not necessarily for the search component, but for modal e.g. Maybe it is easier to provide an option to hide the label?

`OcModal` can continue to use the `OcTextInput` like it is, because it requires to have the same a11y features like a standalone `OcTextInput`. 👍

**Comment by kulmann** [comment]
Since https://github.com/owncloud/owncloud-design-system/pull/1151 is merged now (which removed a dependency on the oc-text-input component), could you please rebase this PR and then have a look through the documentation if all the occurrences of `oc-text-input` in examples are still rendering correctly? I will do the same after your rebase.

**Comment by JammingBen** [comment]
> Since #1151 is merged now (which removed a dependency on the oc-text-input component), could you please rebase this PR and then have a look through the documentation if all the occurrences of oc-text-input in examples are still rendering correctly? I will do the same after your rebase.

Rebased 🙂  Checking now

**Review by kulmann — APPROVED** [review]
Nice job! 🥇

**Comment by JammingBen** [comment]
Checked `OcModal` and `OcAccordion`, looking good. Although the input in `OcAccordion` kinda has two labels now :D

image

**Comment by kulmann** [comment]
> Checked `OcModal` and `OcAccordion`, looking good. Although the input in `OcAccordion` kinda has two labels now :D
> 
> image

true. you could remove the `<p>Enter some text!</p>` then.

**Review by kulmann — APPROVED** [review]

**Comment by JanAckermann** [comment]
Enter some Text could be the descriptionMessage, but merged, next time 👍

**Comment by kulmann** [comment]
> Enter some Text could be the descriptionMessage, but merged, next time 👍

Create a PR ;-) happy to have it changed.

**Pull request merged**
