### PR TITLE
Render a component/template in fullscreen

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

this add a button with will render the component in full screen - this helps in designing the component for different screen sizes

Screenshot from 2019-04-03 18-20-44

## ToDo
- [x] the background needs to be set properly

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
now white ....

Screenshot from 2019-04-03 18-41-46

**Comment by michaelstingl** [comment]
This is a great idea! Something we should contribute upstream?

**Comment by DeepDiver1975** [comment]
> After entering into fullscreen the button disappears. If I leave it then I can't go back into it without refreshing the page

@LukasHirt take care of - please review - THX

**Comment by LukasHirt** [comment]
> > After entering into fullscreen the button disappears. If I leave it then I can't go back into it without refreshing the page
> 
> @LukasHirt take care of - please review - THX

Yes, works fine now. Also I wasn't able to scroll in the full screen. But that was fixed with just adding overflow: auto, so I fixed it already.

**Pull request merged**
