### PR TITLE
Added padding and border to app sidebar

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Added padding, created styles file for oc-app-side-bar and added option to add border on the side.

## Motivation
Padding to let the content breath a little bit and border to properly separate it from other content.

## Screenshot
image

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@felixheidecke please have a look - THX

**Comment by felixheidecke** [comment]
From my POV having a border or not should be a decision by the theme. My concerns:

* App developer interferes with theming _(activating the border-prop for a borderless theme?)_
* Theme interferes with developer decision _(removing the border-class for a borderless theme?)_

@LukasHirt

**Comment by LukasHirt** [comment]
> From my POV having a border or not should be a decision by the theme. My concerns:
> 
> * App developer interferes with theming _(activating the border-prop for a borderless theme?)_
> * Theme interferes with developer decision _(removing the border-class for a borderless theme?)_
> 
> @LukasHirt

Hmm, we will allow borderless theme?

**Comment by felixheidecke** [comment]
> Hmm, we will allow borderless theme?

Well of course we do. Otherwise, it would defeat the purpose of theming … right?

Let's not forget, theming is more than switching colors around.

themes-color-pallets

**Comment by LukasHirt** [comment]
@felixheidecke Border is gone now. Review pls

**Pull request closed without merging**
