### PR TITLE
#1457 Ocswitch off state color

### LINKED ISSUE #1457: OcSwitch: state is (visually) not clear
### Steps to reproduce
1. Trigger the OcSwitch, e.g. as used in the `Show hidden files` in ownCloud Web 

### Expected behaviour
Immediately know if the state is `on` or `off`

### Actual behaviour
Not so sure about the state. The position of the switch (left or right) gives a good hint. But the colors of the `on` and `off` state are pretty similar.

### Screenshots (if appropriate):
Screenshot 2021-07-01 at 16 55 21
Screenshot 2021-07-01 at 16 55 26

### PR DESCRIPTION
**Pull request by paulcod3**
## Description
See #1457 

## Related Issue

- Fixes #1457 

## Motivation and Context
See changelog

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [x] Visual changes

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

### CODE REVIEW

**Review by pascalwengerter — APPROVED** [review]
LGTM 🔛

**Review by kulmann — CHANGES_REQUESTED** [review]
~Please change the name of the changelog item to a `bugfix-` prefix instead of an `enhancement-` prefix.~ sorry, of course this is an enhancement, so the first line within the changelog was wrong. Thanks for fixing it.

**Review by kulmann — CHANGES_REQUESTED** [review]
Could you drop the commitid `af6edb74bd4234f68c9ad27aed97cd09d55da9a1` from this PR?

**Review by kulmann — APPROVED** [review]
LGTM 🥳

**Pull request merged**
