### PR TITLE
Enhancement: Give OcModal the option to use OcContextualHelper

### PR DESCRIPTION
**Pull request by lookacat**
## Description
See https://github.com/owncloud/web/issues/6892#issuecomment-1245438400

## Related Issue
https://github.com/owncloud/web/issues/6892

## Motivation and Context
**Why new props instead of using slot:** So we can use it via code without markup

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests updated
- [ ] Acceptance tests added
- [x] Documentation added/updated

### CODE REVIEW

**Comment by JanAckermann** [comment]
I am not quite sure if we should do this. 
It would be better to use a slot for the message and implement the contextualHelper there.

**Comment by lookacat** [comment]
The slot method is not suitable because we create the modal via code, we have no option there to dynamically provide a template

**Comment by JanAckermann** [comment]
As far as I know it will be rendered in the code via vue template anyways. 
As far as I know, we do the same with text inputs, so it should be quite possible to add a new variable for the ct helper in web. 

It's just not a good approach at the end to add every component we have to the modal it self.

**Comment by JanAckermann** [comment]
Rechecked, the slot won't be used in the app.vue, so I agree that's the easiest solution here.

**Review by JanAckermann — APPROVED** [review]

**Pull request merged**
