### PR TITLE
Add transition to accordion items and increase space

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
😍 

Only needs a changelog item. Then good to go?

**Comment by kulmann** [comment]
@LukasHirt could you revive this PR?

**Comment by LukasHirt** [comment]
> could you revive this PR?

@kulmann I'll do so in the next sprint. Not sure if I could squash it in this one already.

**Comment by pascalwengerter** [comment]
@kulmann @LukasHirt should I rebase & refactor this one? Not sure what has happened to the accordions since December 2020

**Comment by kulmann** [comment]
Accordion received a little facelift regarding focus styles and html structure, not much else. Rebase would be awesome, thanks! The idea of this PR is good. I have no idea what was blocking from finishing it. @LukasHirt your memory is needed here ;-)

**Comment by LukasHirt** [comment]
Hmm, I'll need to pull and build the code to see what was actually missing but I think there was some small bug/ugliness with the transition

**Comment by LukasHirt** [comment]
Closing as the component might get deprecated.

**Pull request closed without merging**
