### PR TITLE
[unit-tests] Added unit tests for OcNotifications component

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
Added unit tests for `OcNotifications` component

## Related Issue

- Part of #1366 

## How Has This Been Tested?

- 💇🏼‍♂️ 
- 🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by individual-it — CHANGES_REQUESTED** [review]
what is the rename doing? I cannot even see a change in the file name

**Comment by kiranparajuli589** [comment]
> what is the rename doing? I cannot even see a change in the file name

every component is started with `Oc`. IMO this was a typo, I've renamed  `OC` to `Oc`

**Review by individual-it — COMMENTED** [review]
looks good
@LukasHirt @kulmann will the rename break anything?

**Comment by LukasHirt** [comment]
> will the rename break anything?

Rename should be fine :+1:

**Review by individual-it — APPROVED** [review]

**Pull request merged**
