### PR TITLE
add initial sharing sidebar

### PR DESCRIPTION
**Pull request by butonic**
adds a sharing sidebar based on

Auswahl_017

- [ ] Why is oc-icon a span but oc-star a div?
- [ ] oc-radios cannot have content?

Screenshot_2019-04-01 ownCloud Design System

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
>     * oc-radios cannot have content?

#143

**Comment by pmaier1** [comment]
Nice! The roles look a little squeezed to me, though.

**Comment by butonic** [comment]
margins, backrounds and styling is something for a css guru ... not me ;-) maybe @ChrisEdS wants to jump in and get his hands dirty?

**Comment by ChrisEdS** [comment]
@LukasHirt is our new man with CSS Guru characteristics. He will certainly be happy to lay his hands on here. //cc @butonic

**Comment by DeepDiver1975** [comment]
> Nice! The roles look a little squeezed to me, though.

we will use this now as the basis for implementing this within phoenix

**Comment by DeepDiver1975** [comment]
closing this - the sidebar is currently being implemented in phoenix

**Pull request closed without merging**
