### PR TITLE
Scaffold accessibility documentation for OcNotification/Message components

### PR DESCRIPTION
**Pull request by marcus-herrmann**
# What's in this PR
* New: added `aria-live` and `role` attributes to the part of the notification container that has text inside it
* New: The amount of interrupting the screen reader (assertive, polite) is indirectly controllable with `<oc-notification-message>`'s `status`: Only "danger" creates an assertive screen reader notification that interrupts the screen reader output
* Changed: The close button is now an actual button (instead of link)
* Changed: The close button has an accessible name of "Close" 
* Added: Documentation

### CODE REVIEW

**Comment by PVince81** [comment]
@LukasHirt @marcus-herrmann is this mergable now ?

**Comment by marcus-herrmann** [comment]
Should be fine since I did not change the components API

**Comment by PVince81** [comment]
@marcus-herrmann can you resolve the conflict and retest ? then I think we can merge this

**Comment by marcus-herrmann** [comment]
@PVince81 Resolved and retested in ODS

**Pull request merged**
