### PR TITLE
Release 3.2.1

### PR DESCRIPTION
**Pull request by kulmann**
This PR fixes a visual bug with displaying folder names that contain a dot (`.`). Most importantly it also adds a `resource-type` attribute to the oc-resource-name component which is required for testing. Otherwise we don't have a way to detect if a resource is a file or folder.

We need to create a release v3.2.1 from this PR and merge it back to master after the release. Do not merge until the release is done. Current master contains changes that we can't release, yet.

### CODE REVIEW

**Review by JammingBen — APPROVED** [review]
LGTM 🚀

**Comment by JammingBen** [comment]
...although it's quite confusing that the `name` and the filename in `path` differ. With this change, this is even more noticable. If there is no specific reason for that, I suggest to equalized those values.

image

**Comment by kulmann** [comment]
> ...although it's quite confusing that the `name` and the filename in `path` differ. With this change, this is even more noticable. If there is no specific reason for that, I suggest to equalize those values.
> 
> image

Hit the `request changes` button, this is a bug, at least in the example ;-) Thanks for spotting it. Checking...

**Review by JammingBen — CHANGES_REQUESTED** [review]
see https://github.com/owncloud/owncloud-design-system/pull/1153#issuecomment-801056362

**Review by JammingBen — APPROVED** [review]
Here we go!

**Comment by kulmann** [comment]
Release done. Merging.

**Pull request merged**
