### PR TITLE
Pre Release 11.2.3

### PR DESCRIPTION
**Pull request by paulnebr**
Pre Release 11.2.3

### CODE REVIEW

**Review by pascalwengerter — COMMENTED** [review]
This PR publishes two enhancements, shouldn't it be a minor version bymp then (aka 11.3.0-rc1 or sth?)

**Review by kulmann — CHANGES_REQUESTED** [review]
Since the changelog items contain `enhancement` items, the minor version needs to be increased. New version should have been `11.3.0-rc1`.

**Comment by kulmann** [comment]
> This PR publishes two enhancements, shouldn't it be a minor version bymp then (aka 11.3.0-rc1 or sth?)

Lol didn't even see your comment. Yeah, that.

**Comment by kulmann** [comment]
Superseded by https://github.com/owncloud/owncloud-design-system/pull/1800

**Pull request closed without merging**
