### PR TITLE
Reorder oc-drop example data, add focus border to li a elements

### PR DESCRIPTION
**Pull request by JanAckermann**

### CODE REVIEW

**Review by pascalwengerter — COMMENTED** [review]
Works great in Chrome, but not in Firefox (buttons are tab-abled and the nav expands on hitting enter, but then you can't "tab through the links") and Safari seems completely broken, at least when checking in the design system docs locally...

**Comment by JanAckermann** [comment]
@pascalwengerter can you check again Chrome and FF works now

**Comment by JammingBen** [comment]
>  and Safari seems completely broken, at least when checking in the design system docs locally...

FF is completely broken for me, too :( I haven't seen an outline throughout the entire ODS.

**Comment by pascalwengerter** [comment]
> @pascalwengerter can you check again Chrome and FF works now

Just did, still doesn't work. Was it the goal of this PR to fix it, anyways?

**Comment by JammingBen** [comment]
> Was it the goal of this PR to fix it, anyways?

Since it seems to be a general problem, I'd say it's not scope of this PR.

**Review by pascalwengerter — APPROVED** [review]
Looks good for now 🤘🏽 focus management / tab navigation are somewhat broken in Firefox/Safari but that's out of scope

**Review by kulmann — APPROVED** [review]

**Pull request merged**
