### PR TITLE
Add support for two-lined file element

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Screenshot from 2019-11-06 17-45-43

### CODE REVIEW

**Comment by wuenschedesign** [comment]
1) draft for a two lined concept of displaying indicators:
List-View-Closed

2) Draft for a concept with columns showing indicators:
List-View-Columns-01

**Comment by wuenschedesign** [comment]
List View with actions:

List-View-Closed-Menue-Actions

**Comment by marcus-herrmann** [comment]
Modal related links: https://developer.paciellogroup.com/blog/2018/06/the-current-state-of-modal-dialog-accessibility/
https://www.scottohara.me/blog/2019/03/05/open-dialog.html

**Comment by wuenschedesign** [comment]
List-View-Detail-Open (1)

**Comment by PVince81** [comment]
Further notes:
- note: inline actions need to be repeated inside the three dots: this helps clarify the icons without having tooltip/inline text
- [ ] examine the solution about: indicators are inside a big button, and big button opens a dropdown in which each row has: one icon + matching state/text. Accessibility: react on focus. => please provide a mock up for this
- [ ] @wuenschedesign: as discussed, we need a mock up for the hybrid version: size+mtime as columns but indicators below the text + a responsive view for mobile

After discussion we agreed to explore the hybrid variant.

**Comment by wuenschedesign** [comment]
Updated View for the file list:
List-View-Closed-02

Actions menu for the fole/file indicators:
List-View-Closed-02-Indicators-Actions-Menu

**Comment by wuenschedesign** [comment]
Mobile views of the file list:

View A | View B
-- | --
List-View-Closed-02-Mobile-B | List-View-Closed-02-Mobile-C

View C | View D
-- | --
List-View-Closed-02-Mobile-D | List-View-Closed-02-Mobile-E

View E | View F
-- | --
 | List-View-Closed-02-Mobile-F | List-View-Closed-02-Mobile-G

**Pull request closed without merging**
