### PR TITLE
A11y fix sufficient contrast

### PR DESCRIPTION
**Pull request by stevefrenzel**
## Description
Changed the border color for inputs and checkboxes so it has a contrast ratio of at least 3:1. New contrast ratio is now 7.01:1.

## Related Issue
- Works towards https://github.com/owncloud/web/issues/5386

## How Has This Been Tested?
- Used this contrast checker to determine the right color: https://webaim.org/resources/contrastchecker/

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added/updated

## Open tasks:

**Page 1 (Alle Dateien)**
When creating a public link in the case the user doesn’t fill the fields a error message appears above the form. This error message has a „X“ button on the right (to remove the message). Here the contrast ration to the background color is lower than 3:1.

Not able to reproduce this scenario, as there is no error message being displayed. Instead the submit button is just disabled as long the required input field is empty.

### CODE REVIEW

**Comment by kulmann** [comment]
I changed the description so that it doesn't say `fixes` anymore, but `Works towards`, because the linked issue is not entirely fixed.

**Comment by kulmann** [comment]
This creates followup-issues (which is ok). First one I see (and didn't dig deeper) is that the `upload progress` component in `web` uses the `oc-color-input-border` variable as a background. Which sounds slightly wrong, so it probably makes sense to exchange that color in `web`.

**Comment by kulmann** [comment]
Comparing old vs new, I think that the checkboxes now look too heavy / prominent in the web ui. They are not the primary element in the files list, so it doesn't feel right, UX wise, to give them this much attention. Please see screenshots below. Can you please try a compromise? Like contrast ratio 4:1 or 5:1?

Screenshot 2021-11-04 at 08 58 24
Screenshot 2021-11-04 at 08 58 39

**Comment by stevefrenzel** [comment]
> Comparing old vs new, I think that the checkboxes now look too heavy / prominent in the web ui. They are not the primary element in the files list, so it doesn't feel right, UX wise, to give them this much attention. Please see screenshots below. Can you please try a compromise? Like contrast ratio 4:1 or 5:1?
> 
> Screenshot 2021-11-04 at 08 58 24
> 
> Screenshot 2021-11-04 at 08 58 39

Input border color now has a ratio of 4.5:1, hope that works for you?

**Comment by stevefrenzel** [comment]
> This creates followup-issues (which is ok). First one I see (and didn't dig deeper) is that the `upload progress` component in `web` uses the `oc-color-input-border` variable as a background. Which sounds slightly wrong, so it probably makes sense to exchange that color in `web`.

If I'm not mistaken this component uses `--oc-color-border` but not `--oc-color-input-border`, which sound dangerously similar but has a completely different color.

**Comment by pascalwengerter** [comment]
> > This creates followup-issues (which is ok). First one I see (and didn't dig deeper) is that the `upload progress` component in `web` uses the `oc-color-input-border` variable as a background. Which sounds slightly wrong, so it probably makes sense to exchange that color in `web`.
> 
> If I'm not mistaken this component uses `--oc-color-border` but not `--oc-color-input-border`, which sound dangerously similar but has a completely different color.

This seems to be the case, so technically resolved

**Comment by pascalwengerter** [comment]
> > Comparing old vs new, I think that the checkboxes now look too heavy / prominent in the web ui. They are not the primary element in the files list, so it doesn't feel right, UX wise, to give them this much attention. Please see screenshots below. Can you please try a compromise? Like contrast ratio 4:1 or 5:1?
> > Screenshot 2021-11-04 at 08 58 24
> > Screenshot 2021-11-04 at 08 58 39
> 
> Input border color now has a ratio of 4.5:1, hope that works for you?

I'll merge "as is" and we can discuss how much contrast we want when we do the backporting, quite a lot has changed since the audit in terms of UI design

**Pull request merged**
