### PR TITLE
relocate oc-table-files to web

### PR DESCRIPTION
**Pull request by fschade**
## Description
ods oc-table-files always contained concrete web-app-files logic, to make development more agile and keep things close
oc-table-files was removed from ODS and relocated to live in web-app-files from now on.

## Related Issue
- https://github.com/owncloud/web/pull/6106

## Motivation and Context
its unnecessarily much work if oc-table-files live in ODS, to have it relocated makes development easier

## How Has This Been Tested?
- unit tests

## Types of changes
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Technical debt

## Checklist:
- [X] tests removed

### CODE REVIEW

**Review by pascalwengerter — COMMENTED** [review]
Most likely needs to extract https://github.com/owncloud/owncloud-design-system/blob/d67d299f1e6b3f0fd204e4501836d275b9fdb3ec/src/components/molecules/OcTable/GhostElement/GhostElement.vue

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
Please adjust https://github.com/owncloud/owncloud-design-system/blob/d67d299f1e6b3f0fd204e4501836d275b9fdb3ec/src/components/molecules/OcTable/GhostElement/GhostElement.vue#L10 (docs update regarding ghost element usage), that'd be it from my side. Otherwise LGTM

**Review by pascalwengerter — APPROVED** [review]
LGTM

**Review by kulmann — APPROVED** [review]
👍

**Pull request merged**
